name: Flutter

# on:
#   push:
#     tags:
#       -"v*.*.*"

on:
  push:
    branches:
      - main

jobs:
  flutter_test:
    name: Run Flutter Test and Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter 3.0.3
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.3"
          channel: "stable"

      - name: Run Flutter Pub Get
        run: flutter pub get

      - name: Run Flutter Analyze
        run: flutter analyze

      # - name: Run Flutter Test
      #   run: flutter test

  build_apk_and_ios:
    name: Build Flutter Apk & iOS
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Flutter 3.0.3
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.3"
          channel: "stable"

      - name: Run Flutter Build to Apk
        run: flutter build apk

      - name: Run Flutter Build to iOs
        run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload

      # - name: Replace YAML version with tag version
      #   run: |
      #     sed -i 's/99.99.99+99/'$GIT_TAG_NAME'/g' pubspec.yaml|
      #     echo "Tag used version:"$GIT_TAG_NAME

      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk,build/ios/iphoneos/app.ipa"
          tag: v1.0.${{ github.run_number }}
